name: SMP
main: me.Asylx.SMP
version: ${project.version}
api-version: 1.13
author: Asylx
depend: [Vault]

commands:
  randomtp:
    description: SMP
    aliases:
      - rtp
  balance:
    description: balance
    aliases: [bal]